resources:
- ../../../../../components/rhtas-operator/operator/base
- ../../../../../components/rhtas-operator/instance/base

patches:
- patch: |
    - op: replace
      path: /spec/fulcio/config/OIDCIssuers/0/Issuer
      value: https://sso.ocplab.com/realms/ocplab
    - op: replace
      path: /spec/fulcio/config/OIDCIssuers/0/IssuerURL
      value: https://sso.ocplab.com/realms/ocplab
  target:
    kind: Securesign
