apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/consolelinks/base
  - acs-consolelink.yaml
  - nexus-consolelink.yaml
  - sonarqube-consolelink.yaml
  - tekton-hub-link.yaml
