apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: medium
  namespace: namespace-configuration-operator
spec:
  labelSelector:
    matchLabels:
      size: medium
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: medium
        namespace: {{ .Name }}
      spec:
        hard:
          requests.cpu: "4"
          requests.memory: "2Gi"
          limits.memory: "4Gi"
  - objectTemplate: |
      apiVersion: "v1"
      kind: "LimitRange"
      metadata:
        name: "medium"
        namespace: {{ .Name }}
      spec:
        limits:
          - type: "Container"
            default:
              memory: "2Gi"
            defaultRequest:
              cpu: "200m"
              memory: "256Mi"