apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small
  namespace: namespace-configuration-operator
spec:
  labelSelector:
    matchLabels:
      size: small
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: small
        namespace: {{ .Name }}
      spec:
        hard:
          requests.cpu: "2"
          requests.memory: "1Gi"
          limits.memory: "2Gi"
  - objectTemplate: |
      apiVersion: "v1"
      kind: "LimitRange"
      metadata:
        name: "small"
        namespace: {{ .Name }}
      spec:
        limits:
          - type: "Container"
            default:
              memory: "1Gi"
            defaultRequest:
              cpu: "100m"
              memory: "256Mi"