apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: 3scale
spec:
  resourceRequirementsEnabled: true
  wildcardDomain: 3scale.apps.home.ocplab.com
  system:
    database:
      postgresql:
        persistentVolumeClaim:
          storageClassName: iscsi
    redisPersistentVolumeClaim:
      storageClassName: iscsi
    fileStorage:
      persistentVolumeClaim:
        storageClassName: managed-nfs-storage
    redisResources:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 4Gi
  backend:
    redisPersistentVolumeClaim:
      storageClassName: iscsi
    redisResources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 150m
        memory: 256Mi
  fileStorage:
    persistentVolumeClaim:
      storageClassName: managed-nfs-storage
