namespace: gitops

resources:
- namespace.yaml
- ../../../../components/apps/gitops-operator/base
- console-link.yaml
- global-appproject.yaml
# Tenant projects here
- product-catalog-appproject.yaml

patches:
# Update permissions for tenants and local accounts
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: ACCOUNTS_NAMESPACES
          value: "product-catalog-pipeline=product-catalog-cicd"
        - name: ARGO_SERVER_HOST
          value: "argocd-server-gitops.apps.home.ocplab.com"
  target:
    kind: Job
    name: create-pipeline-local-user
-  target:
     kind: ArgoCD
     name: argocd
   patch: |-
    - op: add
      path: /spec/extraConfig
      value:
        globalProjects: |-
          - labelSelector:
              matchExpressions:
                - key: argocd.argoproj.io/project-inherit
                  operator: In
                  values:
                    - global
            projectName: global
        accounts.product-catalog-pipeline: apiKey
    - op: add
      path: /spec/sourceNamespaces
      value:
        - product-catalog-gitops
    - op: add
      path: /spec/rbac
      value:
        policy: |
          p, role:product-catalog-pipeline, projects, get, apps-product-catalog, allow
          p, role:product-catalog-pipeline, applications, get, apps-product-catalog/*, allow
          p, role:product-catalog-pipeline, applications, sync, apps-product-catalog/*, allow
          p, role:product-catalog-admin, clusters, get, *, allow
          p, role:product-catalog-admin, projects, get, apps-product-catalog, allow
          p, role:product-catalog-admin, applications, *, apps-product-catalog/*, allow
          p, role:product-catalog-user, clusters, get, *, allow
          p, role:product-catalog-user, projects, get, apps-product-catalog, allow
          p, role:product-catalog-user, applications, get, apps-product-catalog/*, allow
          p, role:product-catalog-user, applications, sync, apps-product-catalog/*, allow
          g, product-catalog-admins, role:product-catalog-admin
          g, product-catalog-users, role:product-catalog-user
          g, cluster-admins, role:admin
          g, product-catalog-pipeline, role:product-catalog-pipeline
        scopes: "[accounts,groups]"