apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: quay

resources:
- ../../../../../../components/apps/quay-registry-operator/overlays/default
- init-user-password-secret.yaml
- init-quay-job.yaml
- set-minimum-sizing-job.yaml
- registry-config-bundle-secret.yaml
- registry.yaml
- registry-app-route.yaml