apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: argocd
spec:
  href: 'https://argocd-server-argocd.apps.home.ocplab.com'
  location: ApplicationMenu
  text: ArgoCD
  applicationMenu:
    section: Tools
    imageURL: https://raw.githubusercontent.com/gnunn-gitops/cluster-config/main/docs/img/argocd-logo.png