apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Don't need these anymore since gitops operator installs them
# - argocd-link.yaml
# - argocd-help-link.yaml
- quay-link.yaml