
- op: add
  path: /users/-
  value: "kubeadmin"
- op: add
  path: /users/-
  value: "opentlc-mgr"
- op: add
  path: /users/-
  value: "admin"
- op: add
  path: /users/-
  value: "gnunn@redhat.com"
- op: add
  path: /users/-
  value: "opentlc-mgr"