apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../../clusterversion/base
- ../../../../../../../components/argocd/apps/sealed-secrets/base
- ../../../../../../../components/argocd/apps/letsencrypt-certs/base
- ../../../../../../../components/argocd/apps/config-storage/base
- ../../../../../../../components/argocd/apps/config-authentication/base
- ../../../../../../../components/argocd/apps/config-groups-and-membership/base
- ../../../../../../../components/argocd/apps/config-alertmanager/base
- ../../../../../../../components/argocd/apps/config-console-links/base
- ../../../../../../../components/argocd/apps/config-helm-repos/base
- ../../../../../../../components/argocd/apps/config-prometheus-user-app/base
- ../../../../../../../components/argocd/apps/config-container-security/base
- ../../../../../../../components/argocd/apps/config-acs/base
- ../../../../../../../components/argocd/apps/config-namespace-config-operator/base
- ../../../../../../../components/argocd/apps/config-web-terminal-operator/base
- ../../../../../../../components/argocd/apps/config-pipeline-operator/base
- ../../../../../../../components/argocd/apps/config-sso/base
- ../../../../../../../components/argocd/apps/config-dev-tools/base
- ../../../../../../../components/argocd/apps/config-cost-management/base
- ../../../../../../../components/argocd/apps/tenant-product-catalog/base
- ../../../../../../../components/argocd/apps/tekton-cluster-tasks/base

patches:
- patch: |-
    - op: replace
      path: /spec/source/path
      value: clusters/local.home/apps/sso/overlays/default
  target:
    kind: Application
    name: config-sso
- patch: |-
    - op: replace
      path: /spec/source/path
      value: clusters/local.home/apps/cost-management-operator/overlays/default
  target:
    kind: Application
    name: config-cost-management