# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-gitops

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

bases:
- ../../../../../components/apps/gitops-operator/base

resources:
- namespace.yaml
- operatorgroup.yaml
- user1-rolebinding.yaml
- product-catalog-project.yaml
- console-link.yaml

patches:
-  target:
     kind: ArgoCD
   patch: |-
    - op: replace
      path: /spec/applicationInstanceLabelKey
      value: argocd.argoproj.io/product-catalog-instance
    - op: add
      path: /spec/rbac
      value:
        defaultPolicy: role:readonly
        policy: |
          g, product-catalog-admins, role:admin
          g, system:cluster-admins, role:admin
        scopes: "[groups]"