apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-admins-group.yaml
- argocdadmins-group-base.yaml
- argocdusers-group-base.yaml
- cluster-admin-users-rolebinding.yaml
# - developer-group-base.yaml