apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-product-catalog
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-namespaces
            path: tenants/product-catalog/namespaces/base
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-gitops
            path: tenants/product-catalog/gitops-operator/overlays/rolebinding
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-rbac
            path: tenants/product-catalog/rbac/base
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-monitor
            path: tenants/product-catalog/monitor/overlays/default
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: tenants
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config
        targetRevision: master
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops