apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- letsencrypt-aws-sealed-secret.yaml
- subscription.yaml
- letsencrypt-prod-cluster-issuer.yaml

