# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secrets-app.yaml
- sealed-secrets-namespace.yaml
- sealed-secrets-secret.yaml