apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-mcp
  template:
    metadata:
      labels:
        app: argocd-mcp
    spec:
      containers:
        - name: argocd-mcp
          image: quay.io/gnunn/mcp-for-argocd:latest
          imagePullPolicy: Always
          command:
            - node
            - dist/index.js
            - sse
          ports:
            - containerPort: 3000
          # env:
          #   - name: ARGOCD_BASE_URL
          #     value: "http://argocd-server.demo-gitops.svc.cluster.local"
          #   - name: ARGOCD_API_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: argocd-secret
          #         key: ARGOCD_API_TOKEN
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
