kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: costmanagement-metrics-operator

resources:
  - https://github.com/redhat-cop/gitops-catalog/cost-management-operator/overlays/aggregate

patchesJson6902:
  - path: patch-source-and-name.yaml
    target:
      group: costmanagement-metrics-cfg.openshift.io
      kind: CostManagementMetricsConfig
      name: config
      version: v1beta1
